// Code generated by "enumer -type=TransferStatus -trimprefix=TransferStatus -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

const _TransferStatusName = "PendingAssignedHandled"

var _TransferStatusIndex = [...]uint8{0, 7, 15, 22}

func (i TransferStatus) String() string {
	i -= 1
	if i >= TransferStatus(len(_TransferStatusIndex)-1) {
		return fmt.Sprintf("TransferStatus(%d)", i+1)
	}
	return _TransferStatusName[_TransferStatusIndex[i]:_TransferStatusIndex[i+1]]
}

var _TransferStatusValues = []TransferStatus{1, 2, 3}

var _TransferStatusNameToValueMap = map[string]TransferStatus{
	_TransferStatusName[0:7]:   1,
	_TransferStatusName[7:15]:  2,
	_TransferStatusName[15:22]: 3,
}

// TransferStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TransferStatusString(s string) (TransferStatus, error) {
	if val, ok := _TransferStatusNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TransferStatus values", s)
}

// TransferStatusValues returns all values of the enum
func TransferStatusValues() []TransferStatus {
	return _TransferStatusValues
}

// IsATransferStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TransferStatus) IsATransferStatus() bool {
	for _, v := range _TransferStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TransferStatus
func (i TransferStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TransferStatus
func (i *TransferStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TransferStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TransferStatusString(s)
	return err
}
