dapp:
  client_id: 69c6a13b-d38e-4b7c-8f39-32933a6dfb1f
  session_id: 3c494d5c-0331-4a08-a364-57e0f56e62a4
  private_key: private key
  session_private_key: session private key

db:
  driver: mysql
  dsn: root:root@tcp
  replicas:
  - root:root@tcp

rpc:
  prefix: /twirp
  blocked_assets :
    - 965e5c6e-434c-3fa9-b780-c50f43cd955c