// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pandodao/safe-wallet/handler/api"
	"github.com/pandodao/safe-wallet/handler/rpc"
	"github.com/pandodao/safe-wallet/service/asset"
	transfer2 "github.com/pandodao/safe-wallet/service/transfer"
	"github.com/pandodao/safe-wallet/store/output"
	"github.com/pandodao/safe-wallet/store/transfer"
	"github.com/spf13/viper"
	"log/slog"
)

// Injectors from wire.go:

func setupApp(v *viper.Viper, logger *slog.Logger) (app, func(), error) {
	db, cleanup, err := provideDB(v)
	if err != nil {
		return app{}, nil, err
	}
	outputStore := output.New(db)
	transferStore := transfer.New(db)
	keystore := provideKeystore(v)
	client, err := provideMixinClient(keystore)
	if err != nil {
		cleanup()
		return app{}, nil, err
	}
	assetService := asset.New(client)
	key := provideSpendKey()
	transferService := transfer2.New(assetService, client, key)
	config := provideRpcConfig(keystore)
	server := rpc.New(outputStore, transferStore, transferService, logger, config)
	apiServer := api.New(server)
	httpServer := provideServer(apiServer, server)
	mainApp := app{
		svr:    httpServer,
		logger: logger,
	}
	return mainApp, func() {
		cleanup()
	}, nil
}
