CREATE TABLE IF NOT EXISTS `properties` (
    `key` VARCHAR(64) PRIMARY KEY,
    `value` JSON NOT NULL,
    `version` BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
